# Generated by Django 4.2.7 on 2024-02-17 00:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(default='', max_length=12, null=True)),
                ('nombrea', models.CharField(max_length=144)),
                ('apellido', models.CharField(max_length=144)),
                ('celular', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=144)),
                ('tipos_especialidad', models.CharField(choices=[('Penal', 'Penal'), ('Laboral', 'Laboral'), ('Civil', 'Civil')], default='Penal', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Casos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos_casos', models.CharField(choices=[('Penal', 'Penal'), ('laboral', 'Laboral'), ('Civil', 'Civil')], default='Penal', max_length=10)),
                ('Estado', models.CharField(choices=[('Proceso', 'Proceso'), ('Cerrado', 'Cerrado')], default='Proceso', max_length=10)),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('abogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='login.abogado')),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(default='', max_length=12, null=True)),
                ('nombrec', models.CharField(max_length=144)),
                ('apellido', models.CharField(max_length=144)),
                ('direccion', models.CharField(max_length=144)),
                ('celular', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=144)),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion_documento', models.TextField()),
                ('archivo_adjunto', models.FileField(blank=True, upload_to='documentos/')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.casos')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateTimeField()),
                ('lugar_cita', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('abogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='login.abogado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='login.clientes')),
            ],
        ),
        migrations.AddField(
            model_name='casos',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='login.clientes'),
        ),
    ]
