# Generated by Django 5.0.2 on 2024-02-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_clientes_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_Abogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutolo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='media/fotos/')),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
