# Generated by Django 5.0.2 on 2024-02-20 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_info_abogado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info_abogado',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='info_abogado',
            name='tutolo',
        ),
        migrations.AddField(
            model_name='abogado',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto del perro.', null=True, upload_to='media/', verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='info_abogado',
            name='abogado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='login.abogado'),
        ),
    ]
