# Generated by Django 5.0.2 on 2024-02-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_info_abogado_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='foto',
            field=models.ImageField(blank=True, help_text='foto.', null=True, upload_to='media/', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='info_abogado',
            name='descripcion',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
