# Generated by Django 4.2.7 on 2024-02-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_perfil_usuario'),
        ('login', '0005_alter_abogado_foto_alter_info_abogado_descripcion'),
    ]

    operations = [
    ]
