# Generated by Django 4.2.7 on 2024-02-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_merge_20240220_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casos',
            name='tipos_casos',
            field=models.CharField(choices=[('Penal', 'Penal'), ('Laboral', 'Laboral'), ('Civil', 'Civil')], default='Penal', max_length=10),
        ),
    ]
