# Generated by Django 4.2.7 on 2024-02-21 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_casos_tipos_casos'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil_usuario',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_usuarios', to='login.clientes'),
        ),
    ]
