# Generated by Django 4.2.7 on 2024-02-21 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_perfil_usuario_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_usuario',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_usuarios', to='login.clientes'),
        ),
    ]
