# Generated by Django 4.2.7 on 2024-02-21 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_abogado_foto'),
        ('login', '0009_alter_perfil_usuario_cliente'),
    ]

    operations = [
    ]
