# Generated by Django 5.0.2 on 2024-02-21 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_abogado_foto'),
        ('login', '0009_alter_perfil_usuario_cliente'),
    ]

    operations = [
    ]
