# Generated by Django 5.0.2 on 2024-02-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_abogado_descripcion_abogado_experiencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
