# Generated by Django 5.0.2 on 2024-02-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_merge_20240220_2236'),
        ('login', '0012_alter_abogado_descripcion'),
    ]

    operations = [
    ]
