# Generated by Django 4.2.7 on 2024-02-22 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_abogado_user_clientes_user_delete_perfil_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abogado',
            name='user',
        ),
    ]
