# Generated by Django 4.2.7 on 2024-02-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_abogado_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='casos',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
