# Generated by Django 4.2.7 on 2024-02-27 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_alter_horario_atencion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario_atencion',
            options={},
        ),
    ]
