# Generated by Django 4.2.7 on 2024-02-27 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_cita1_hora_elegida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita1',
            name='hora_elegida',
        ),
    ]
