# Generated by Django 4.2.7 on 2024-02-27 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_remove_cita1_hora_elegida'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita1',
            name='abogado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cita1', to='login.abogado'),
            preserve_default=False,
        ),
    ]
