# Generated by Django 4.2.7 on 2024-02-27 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_cita1_abogado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita1',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.clientes'),
        ),
    ]
