# Generated by Django 4.2.7 on 2024-02-27 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_alter_cita1_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita1',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cita1', to='login.clientes'),
        ),
    ]
