# Generated by Django 4.2.7 on 2024-02-27 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_alter_cita1_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cita',
        ),
    ]
