# Generated by Django 4.2.10 on 2024-03-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0028_delete_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='casos',
            name='historial_actualizaciones',
            field=models.TextField(blank=True),
        ),
    ]
